import StatCard from '../components/StatCard';

function AdminDashboard() {
  return (
    <div className="dashboard-page"><div className="dashboard-heading"><div><span className="section-kicker">Centro de controle</span><h1>Visão da plataforma</h1><p>Indicadores principais do AutoMatch AI.</p></div></div><div className="stats-grid"><StatCard label="Usuários cadastrados" value="8.492" detail="+12,4% este mês" accent /><StatCard label="Veículos anunciados" value="3.184" detail="428 ativos agora" /><StatCard label="Vendedores" value="1.026" detail="34 novos este mês" /><StatCard label="Negociações" value="684" detail="+8,2% esta semana" /><StatCard label="Novos usuários" value="126" detail="Últimos 7 dias" /></div><div className="admin-columns"><section className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">Monitoramento</span><h2>Atividade recente</h2></div></div><ul className="activity-list"><li><span className="activity-dot green" /><div><strong>Novo anúncio publicado</strong><span>Honda Civic · há 8 min</span></div></li><li><span className="activity-dot" /><div><strong>Negociação iniciada</strong><span>Corolla Cross · há 24 min</span></div></li><li><span className="activity-dot orange" /><div><strong>Usuário cadastrado</strong><span>Marina Alves · há 41 min</span></div></li></ul></section><section className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">Inventário</span><h2>Veículos recentes</h2></div></div><div className="compact-list"><div><strong>BMW 320i M Sport</strong><span>R$ 219.900 · Belo Horizonte</span></div><div><strong>Fiat Pulse Precision</strong><span>R$ 124.900 · Rio de Janeiro</span></div><div><strong>Hyundai Creta Comfort</strong><span>R$ 119.800 · Porto Alegre</span></div></div></section></div><section className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">Comunidade</span><h2>Novos usuários</h2></div></div><div className="user-row"><span className="avatar small">MA</span><div><strong>Marina Alves</strong><span>Cliente · hoje, 10:42</span></div><span className="user-role">Cliente</span></div><div className="user-row"><span className="avatar small alt">RS</span><div><strong>Rafael Souza</strong><span>Vendedor · hoje, 09:18</span></div><span className="user-role">Vendedor</span></div></section></div>
  );
}

export default AdminDashboard;
